server:
  port: 9998
  undertow:
    #(NIO直接分配的堆外内存)
    direct-buffers: true
    threads:
      worker: 128
      io: 32
  servlet:
    context-path: /spring-template

#  tomcat:
#    max-connections: 20000
#    accept-count: 1000
#    threads:
#      min-spare: 100
#      max: 500
#    max-swallow-size: -1

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    info:
      enabled: true
    health:
      enabled: false
    metrics:
      enabled: false
    prometheus:
      enabled: false

spring:
  profiles:
    active: local
  application:
    name: spring-template

logging:
  config: classpath:logback-spring.xml
  level:
    com.caijuan: debug